export const KERBEROSEC_HUB_PORT = 25463; // KERBEROSEC
export const KERBEROSEC_HUB_DEV_PORT = 25466; // USED IN DEV ENV ONLY, to avoid conflicts with production KERBEROSEC HUB
export const KERBEROSEC_DEFAULT_RPC_PORT = 4317;
export const RPC_ADDRESS_BASE = "127.0.0.1";
export const KERBEROSEC_DEFAULT_RPC_ADDRESS = `${RPC_ADDRESS_BASE}:${KERBEROSEC_DEFAULT_RPC_PORT}`;
