// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.19.1

/* eslint-disable */

export * as protobuf from "./index.google.protobuf";
