// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts/generate-protobus-setup.mjs
import * as proto from "@shared/proto/index"
import { ProtoBusClient, Callbacks } from "./grpc-client-base"

export class AccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.AccountService"
	static async accountLoginClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest(
			"accountLoginClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
		)
	}
	static async accountLogoutClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"accountLogoutClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static subscribeToAuthStatusUpdate(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.AuthState>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAuthStatusUpdate",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.AuthState.fromJSON,
			callbacks,
		)
	}
	static async authStateChanged(request: proto.kerberosec.AuthStateChangedRequest): Promise<proto.kerberosec.AuthState> {
		return this.makeUnaryRequest(
			"authStateChanged",
			request,
			proto.kerberosec.AuthStateChangedRequest.toJSON,
			proto.kerberosec.AuthState.fromJSON,
		)
	}
	static async getUserCredits(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.UserCreditsData> {
		return this.makeUnaryRequest(
			"getUserCredits",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.UserCreditsData.fromJSON,
		)
	}
	static async getOrganizationCredits(
		request: proto.kerberosec.GetOrganizationCreditsRequest,
	): Promise<proto.kerberosec.OrganizationCreditsData> {
		return this.makeUnaryRequest(
			"getOrganizationCredits",
			request,
			proto.kerberosec.GetOrganizationCreditsRequest.toJSON,
			proto.kerberosec.OrganizationCreditsData.fromJSON,
		)
	}
	static async getUserOrganizations(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.UserOrganizationsResponse> {
		return this.makeUnaryRequest(
			"getUserOrganizations",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.UserOrganizationsResponse.fromJSON,
		)
	}
	static async setUserOrganization(request: proto.kerberosec.UserOrganizationUpdateRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"setUserOrganization",
			request,
			proto.kerberosec.UserOrganizationUpdateRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async openrouterAuthClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openrouterAuthClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async requestyAuthClicked(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"requestyAuthClicked",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async hicapAuthClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"hicapAuthClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async getRedirectUrl(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest(
			"getRedirectUrl",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
		)
	}
	static async openAiCodexSignIn(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openAiCodexSignIn",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async openAiCodexSignOut(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openAiCodexSignOut",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async submitLimitIncreaseRequest(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.SubmitLimitIncreaseResponse> {
		return this.makeUnaryRequest(
			"submitLimitIncreaseRequest",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.SubmitLimitIncreaseResponse.fromJSON,
		)
	}
}
export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.BrowserService"
	static async getBrowserConnectionInfo(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.BrowserConnectionInfo> {
		return this.makeUnaryRequest(
			"getBrowserConnectionInfo",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.BrowserConnectionInfo.fromJSON,
		)
	}
	static async testBrowserConnection(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.BrowserConnection> {
		return this.makeUnaryRequest(
			"testBrowserConnection",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.BrowserConnection.fromJSON,
		)
	}
	static async discoverBrowser(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.BrowserConnection> {
		return this.makeUnaryRequest(
			"discoverBrowser",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.BrowserConnection.fromJSON,
		)
	}
	static async getDetectedChromePath(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.ChromePath> {
		return this.makeUnaryRequest(
			"getDetectedChromePath",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.ChromePath.fromJSON,
		)
	}
	static async relaunchChromeDebugMode(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest(
			"relaunchChromeDebugMode",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
		)
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.CheckpointsService"
	static async checkpointRestore(request: proto.kerberosec.CheckpointRestoreRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"checkpointRestore",
			request,
			proto.kerberosec.CheckpointRestoreRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async checkpointViewLatestChanges(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"checkpointViewLatestChanges",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async checkpointLatestChangesCount(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Int64> {
		return this.makeUnaryRequest(
			"checkpointLatestChangesCount",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Int64.fromJSON,
		)
	}
}
export class CommandsServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.CommandsService"
	static async addToKerberoSec(request: proto.kerberosec.CommandContext): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"addToKerberoSec",
			request,
			proto.kerberosec.CommandContext.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async fixWithKerberoSec(request: proto.kerberosec.CommandContext): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"fixWithKerberoSec",
			request,
			proto.kerberosec.CommandContext.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async explainWithKerberoSec(request: proto.kerberosec.CommandContext): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"explainWithKerberoSec",
			request,
			proto.kerberosec.CommandContext.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async improveWithKerberoSec(request: proto.kerberosec.CommandContext): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"improveWithKerberoSec",
			request,
			proto.kerberosec.CommandContext.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.FileService"
	static async copyToClipboard(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"copyToClipboard",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async openFile(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("openFile", request, proto.kerberosec.StringRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async openImage(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("openImage", request, proto.kerberosec.StringRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async openMention(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openMention",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async deleteRuleFile(request: proto.kerberosec.RuleFileRequest): Promise<proto.kerberosec.RuleFile> {
		return this.makeUnaryRequest(
			"deleteRuleFile",
			request,
			proto.kerberosec.RuleFileRequest.toJSON,
			proto.kerberosec.RuleFile.fromJSON,
		)
	}
	static async createRuleFile(request: proto.kerberosec.RuleFileRequest): Promise<proto.kerberosec.RuleFile> {
		return this.makeUnaryRequest(
			"createRuleFile",
			request,
			proto.kerberosec.RuleFileRequest.toJSON,
			proto.kerberosec.RuleFile.fromJSON,
		)
	}
	static async searchCommits(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.GitCommits> {
		return this.makeUnaryRequest(
			"searchCommits",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.GitCommits.fromJSON,
		)
	}
	static async selectFiles(request: proto.kerberosec.BooleanRequest): Promise<proto.kerberosec.StringArrays> {
		return this.makeUnaryRequest(
			"selectFiles",
			request,
			proto.kerberosec.BooleanRequest.toJSON,
			proto.kerberosec.StringArrays.fromJSON,
		)
	}
	static async getRelativePaths(request: proto.kerberosec.RelativePathsRequest): Promise<proto.kerberosec.RelativePaths> {
		return this.makeUnaryRequest(
			"getRelativePaths",
			request,
			proto.kerberosec.RelativePathsRequest.toJSON,
			proto.kerberosec.RelativePaths.fromJSON,
		)
	}
	static async searchFiles(request: proto.kerberosec.FileSearchRequest): Promise<proto.kerberosec.FileSearchResults> {
		return this.makeUnaryRequest(
			"searchFiles",
			request,
			proto.kerberosec.FileSearchRequest.toJSON,
			proto.kerberosec.FileSearchResults.fromJSON,
		)
	}
	static async toggleKerberoSecRule(
		request: proto.kerberosec.ToggleKerberoSecRuleRequest,
	): Promise<proto.kerberosec.ToggleKerberoSecRules> {
		return this.makeUnaryRequest(
			"toggleKerberoSecRule",
			request,
			proto.kerberosec.ToggleKerberoSecRuleRequest.toJSON,
			proto.kerberosec.ToggleKerberoSecRules.fromJSON,
		)
	}
	static async toggleCursorRule(
		request: proto.kerberosec.ToggleCursorRuleRequest,
	): Promise<proto.kerberosec.KerberoSecRulesToggles> {
		return this.makeUnaryRequest(
			"toggleCursorRule",
			request,
			proto.kerberosec.ToggleCursorRuleRequest.toJSON,
			proto.kerberosec.KerberoSecRulesToggles.fromJSON,
		)
	}
	static async toggleWindsurfRule(
		request: proto.kerberosec.ToggleWindsurfRuleRequest,
	): Promise<proto.kerberosec.KerberoSecRulesToggles> {
		return this.makeUnaryRequest(
			"toggleWindsurfRule",
			request,
			proto.kerberosec.ToggleWindsurfRuleRequest.toJSON,
			proto.kerberosec.KerberoSecRulesToggles.fromJSON,
		)
	}
	static async toggleAgentsRule(
		request: proto.kerberosec.ToggleAgentsRuleRequest,
	): Promise<proto.kerberosec.KerberoSecRulesToggles> {
		return this.makeUnaryRequest(
			"toggleAgentsRule",
			request,
			proto.kerberosec.ToggleAgentsRuleRequest.toJSON,
			proto.kerberosec.KerberoSecRulesToggles.fromJSON,
		)
	}
	static async refreshRules(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.RefreshedRules> {
		return this.makeUnaryRequest(
			"refreshRules",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.RefreshedRules.fromJSON,
		)
	}
	static async openDiskConversationHistory(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openDiskConversationHistory",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async toggleWorkflow(
		request: proto.kerberosec.ToggleWorkflowRequest,
	): Promise<proto.kerberosec.KerberoSecRulesToggles> {
		return this.makeUnaryRequest(
			"toggleWorkflow",
			request,
			proto.kerberosec.ToggleWorkflowRequest.toJSON,
			proto.kerberosec.KerberoSecRulesToggles.fromJSON,
		)
	}
	static async ifFileExistsRelativePath(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.BooleanResponse> {
		return this.makeUnaryRequest(
			"ifFileExistsRelativePath",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.BooleanResponse.fromJSON,
		)
	}
	static async openFileRelativePath(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openFileRelativePath",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async openFocusChainFile(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openFocusChainFile",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async refreshHooks(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.HooksToggles> {
		return this.makeUnaryRequest(
			"refreshHooks",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.HooksToggles.fromJSON,
		)
	}
	static async toggleHook(request: proto.kerberosec.ToggleHookRequest): Promise<proto.kerberosec.ToggleHookResponse> {
		return this.makeUnaryRequest(
			"toggleHook",
			request,
			proto.kerberosec.ToggleHookRequest.toJSON,
			proto.kerberosec.ToggleHookResponse.fromJSON,
		)
	}
	static async createHook(request: proto.kerberosec.CreateHookRequest): Promise<proto.kerberosec.CreateHookResponse> {
		return this.makeUnaryRequest(
			"createHook",
			request,
			proto.kerberosec.CreateHookRequest.toJSON,
			proto.kerberosec.CreateHookResponse.fromJSON,
		)
	}
	static async deleteHook(request: proto.kerberosec.DeleteHookRequest): Promise<proto.kerberosec.DeleteHookResponse> {
		return this.makeUnaryRequest(
			"deleteHook",
			request,
			proto.kerberosec.DeleteHookRequest.toJSON,
			proto.kerberosec.DeleteHookResponse.fromJSON,
		)
	}
	static async refreshSkills(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.RefreshedSkills> {
		return this.makeUnaryRequest(
			"refreshSkills",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.RefreshedSkills.fromJSON,
		)
	}
	static async toggleSkill(request: proto.kerberosec.ToggleSkillRequest): Promise<proto.kerberosec.SkillsToggles> {
		return this.makeUnaryRequest(
			"toggleSkill",
			request,
			proto.kerberosec.ToggleSkillRequest.toJSON,
			proto.kerberosec.SkillsToggles.fromJSON,
		)
	}
	static async createSkillFile(request: proto.kerberosec.CreateSkillRequest): Promise<proto.kerberosec.SkillsToggles> {
		return this.makeUnaryRequest(
			"createSkillFile",
			request,
			proto.kerberosec.CreateSkillRequest.toJSON,
			proto.kerberosec.SkillsToggles.fromJSON,
		)
	}
	static async deleteSkillFile(request: proto.kerberosec.DeleteSkillRequest): Promise<proto.kerberosec.SkillsToggles> {
		return this.makeUnaryRequest(
			"deleteSkillFile",
			request,
			proto.kerberosec.DeleteSkillRequest.toJSON,
			proto.kerberosec.SkillsToggles.fromJSON,
		)
	}
}
export class MarketplaceServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.MarketplaceService"
	static async getMarketplaceCatalog(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.MarketplaceCatalog> {
		return this.makeUnaryRequest(
			"getMarketplaceCatalog",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.MarketplaceCatalog.fromJSON,
		)
	}
	static async listMarketplaceLocalInstalledEntries(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.MarketplaceLocalInstalledEntries> {
		return this.makeUnaryRequest(
			"listMarketplaceLocalInstalledEntries",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.MarketplaceLocalInstalledEntries.fromJSON,
		)
	}
	static async listMarketplaceInstalledEntries(
		request: proto.kerberosec.MarketplaceEntriesRequest,
	): Promise<proto.kerberosec.MarketplaceInstalledEntries> {
		return this.makeUnaryRequest(
			"listMarketplaceInstalledEntries",
			request,
			proto.kerberosec.MarketplaceEntriesRequest.toJSON,
			proto.kerberosec.MarketplaceInstalledEntries.fromJSON,
		)
	}
	static async installMarketplaceEntry(
		request: proto.kerberosec.MarketplaceEntryRequest,
	): Promise<proto.kerberosec.MarketplaceInstallResult> {
		return this.makeUnaryRequest(
			"installMarketplaceEntry",
			request,
			proto.kerberosec.MarketplaceEntryRequest.toJSON,
			proto.kerberosec.MarketplaceInstallResult.fromJSON,
		)
	}
	static async uninstallMarketplaceEntry(
		request: proto.kerberosec.MarketplaceEntryRequest,
	): Promise<proto.kerberosec.MarketplaceInstallResult> {
		return this.makeUnaryRequest(
			"uninstallMarketplaceEntry",
			request,
			proto.kerberosec.MarketplaceEntryRequest.toJSON,
			proto.kerberosec.MarketplaceInstallResult.fromJSON,
		)
	}
	static async toggleMarketplaceLocalInstalledEntry(
		request: proto.kerberosec.ToggleMarketplaceLocalInstalledEntryRequest,
	): Promise<proto.kerberosec.MarketplaceLocalInstalledEntries> {
		return this.makeUnaryRequest(
			"toggleMarketplaceLocalInstalledEntry",
			request,
			proto.kerberosec.ToggleMarketplaceLocalInstalledEntryRequest.toJSON,
			proto.kerberosec.MarketplaceLocalInstalledEntries.fromJSON,
		)
	}
	static async uninstallMarketplaceLocalInstalledEntry(
		request: proto.kerberosec.MarketplaceLocalInstalledEntryRequest,
	): Promise<proto.kerberosec.MarketplaceInstallResult> {
		return this.makeUnaryRequest(
			"uninstallMarketplaceLocalInstalledEntry",
			request,
			proto.kerberosec.MarketplaceLocalInstalledEntryRequest.toJSON,
			proto.kerberosec.MarketplaceInstallResult.fromJSON,
		)
	}
}
export class McpServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.McpService"
	static async toggleMcpServer(request: proto.kerberosec.ToggleMcpServerRequest): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"toggleMcpServer",
			request,
			proto.kerberosec.ToggleMcpServerRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async updateMcpTimeout(request: proto.kerberosec.UpdateMcpTimeoutRequest): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"updateMcpTimeout",
			request,
			proto.kerberosec.UpdateMcpTimeoutRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async addRemoteMcpServer(request: proto.kerberosec.AddRemoteMcpServerRequest): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"addRemoteMcpServer",
			request,
			proto.kerberosec.AddRemoteMcpServerRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async restartMcpServer(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"restartMcpServer",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async deleteMcpServer(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"deleteMcpServer",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async toggleToolAutoApprove(
		request: proto.kerberosec.ToggleToolAutoApproveRequest,
	): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"toggleToolAutoApprove",
			request,
			proto.kerberosec.ToggleToolAutoApproveRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static async openMcpSettings(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openMcpSettings",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async authenticateMcpServer(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"authenticateMcpServer",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async getLatestMcpServers(request: proto.kerberosec.Empty): Promise<proto.kerberosec.McpServers> {
		return this.makeUnaryRequest(
			"getLatestMcpServers",
			request,
			proto.kerberosec.Empty.toJSON,
			proto.kerberosec.McpServers.fromJSON,
		)
	}
	static subscribeToMcpServers(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.McpServers>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMcpServers",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.McpServers.fromJSON,
			callbacks,
		)
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.ModelsService"
	static async getOllamaModels(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.StringArray> {
		return this.makeUnaryRequest(
			"getOllamaModels",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.StringArray.fromJSON,
		)
	}
	static async getLmStudioModels(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.StringArray> {
		return this.makeUnaryRequest(
			"getLmStudioModels",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.StringArray.fromJSON,
		)
	}
	static async getVsCodeLmModels(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.VsCodeLmModelsArray> {
		return this.makeUnaryRequest(
			"getVsCodeLmModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.VsCodeLmModelsArray.fromJSON,
		)
	}
	static async refreshOpenRouterModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshOpenRouterModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshKerberoSecRecommendedModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.KerberoSecRecommendedModelsResponse> {
		return this.makeUnaryRequest(
			"refreshKerberoSecRecommendedModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.KerberoSecRecommendedModelsResponse.fromJSON,
		)
	}
	static async refreshHuggingFaceModels(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshHuggingFaceModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshOpenAiModels(request: proto.kerberosec.OpenAiModelsRequest): Promise<proto.kerberosec.StringArray> {
		return this.makeUnaryRequest(
			"refreshOpenAiModels",
			request,
			proto.kerberosec.OpenAiModelsRequest.toJSON,
			proto.kerberosec.StringArray.fromJSON,
		)
	}
	static async refreshRequestyModels(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshRequestyModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshHicapModels(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshHicapModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshLiteLlmModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshLiteLlmModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static subscribeToOpenRouterModels(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.OpenRouterCompatibleModelInfo>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToOpenRouterModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		)
	}
	static subscribeToLiteLlmModels(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.OpenRouterCompatibleModelInfo>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToLiteLlmModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		)
	}
	static async updateApiConfigurationProto(
		request: proto.kerberosec.UpdateApiConfigurationRequest,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfigurationProto",
			request,
			proto.kerberosec.UpdateApiConfigurationRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateApiConfiguration(
		request: proto.kerberosec.UpdateApiConfigurationRequestNew,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfiguration",
			request,
			proto.kerberosec.UpdateApiConfigurationRequestNew.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateApiConfigurationPartial(
		request: proto.kerberosec.UpdateApiConfigurationPartialRequest,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfigurationPartial",
			request,
			proto.kerberosec.UpdateApiConfigurationPartialRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async refreshGroqModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshGroqModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshBasetenModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshBasetenModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async getSapAiCoreModels(
		request: proto.kerberosec.SapAiCoreModelsRequest,
	): Promise<proto.kerberosec.SapAiCoreModelsResponse> {
		return this.makeUnaryRequest(
			"getSapAiCoreModels",
			request,
			proto.kerberosec.SapAiCoreModelsRequest.toJSON,
			proto.kerberosec.SapAiCoreModelsResponse.fromJSON,
		)
	}
	static async refreshOcaModels(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.OcaCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshOcaModels",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.OcaCompatibleModelInfo.fromJSON,
		)
	}
	static async getAihubmixModels(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"getAihubmixModels",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async refreshVercelAiGatewayModelsRpc(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshVercelAiGatewayModelsRpc",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OpenRouterCompatibleModelInfo.fromJSON,
		)
	}
	static async listProviders(request: proto.kerberosec.Empty): Promise<proto.kerberosec.ProviderListingsResponse> {
		return this.makeUnaryRequest(
			"listProviders",
			request,
			proto.kerberosec.Empty.toJSON,
			proto.kerberosec.ProviderListingsResponse.fromJSON,
		)
	}
	static async resolveProviderModels(
		request: proto.kerberosec.ResolveProviderModelsRequest,
	): Promise<proto.kerberosec.ProviderModelsResponse> {
		return this.makeUnaryRequest(
			"resolveProviderModels",
			request,
			proto.kerberosec.ResolveProviderModelsRequest.toJSON,
			proto.kerberosec.ProviderModelsResponse.fromJSON,
		)
	}
	static async resolveModelInfo(
		request: proto.kerberosec.ResolveModelInfoRequest,
	): Promise<proto.kerberosec.ResolveModelInfoResponse> {
		return this.makeUnaryRequest(
			"resolveModelInfo",
			request,
			proto.kerberosec.ResolveModelInfoRequest.toJSON,
			proto.kerberosec.ResolveModelInfoResponse.fromJSON,
		)
	}
	static async readProviderConfig(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.ProviderConfigResponse> {
		return this.makeUnaryRequest(
			"readProviderConfig",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.ProviderConfigResponse.fromJSON,
		)
	}
	static async writeProviderConfig(
		request: proto.kerberosec.WriteProviderConfigRequest,
	): Promise<proto.kerberosec.ProviderConfigResponse> {
		return this.makeUnaryRequest(
			"writeProviderConfig",
			request,
			proto.kerberosec.WriteProviderConfigRequest.toJSON,
			proto.kerberosec.ProviderConfigResponse.fromJSON,
		)
	}
	static async commitModelSelection(request: proto.kerberosec.CommitModelSelectionRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"commitModelSelection",
			request,
			proto.kerberosec.CommitModelSelectionRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
}
export class OcaAccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.OcaAccountService"
	static async ocaAccountLoginClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest(
			"ocaAccountLoginClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
		)
	}
	static async ocaAccountLogoutClicked(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"ocaAccountLogoutClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static ocaSubscribeToAuthStatusUpdate(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.OcaAuthState>,
	): () => void {
		return this.makeStreamingRequest(
			"ocaSubscribeToAuthStatusUpdate",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.OcaAuthState.fromJSON,
			callbacks,
		)
	}
}
export class RemoteConfigServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.RemoteConfigService"
	static async getRemoteConfigSettings(
		request: proto.kerberosec.Empty,
	): Promise<proto.kerberosec.RemoteConfigSettingsResponse> {
		return this.makeUnaryRequest(
			"getRemoteConfigSettings",
			request,
			proto.kerberosec.Empty.toJSON,
			proto.kerberosec.RemoteConfigSettingsResponse.fromJSON,
		)
	}
	static async toggleRemoteConfigSetting(
		request: proto.kerberosec.ToggleRemoteConfigSettingRequest,
	): Promise<proto.kerberosec.RemoteConfigSetting> {
		return this.makeUnaryRequest(
			"toggleRemoteConfigSetting",
			request,
			proto.kerberosec.ToggleRemoteConfigSettingRequest.toJSON,
			proto.kerberosec.RemoteConfigSetting.fromJSON,
		)
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.SlashService"
	static async reportBug(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("reportBug", request, proto.kerberosec.StringRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async condense(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("condense", request, proto.kerberosec.StringRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async getAvailableSlashCommands(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.SlashCommandsResponse> {
		return this.makeUnaryRequest(
			"getAvailableSlashCommands",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.SlashCommandsResponse.fromJSON,
		)
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.StateService"
	static async getLatestState(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.State> {
		return this.makeUnaryRequest(
			"getLatestState",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.State.fromJSON,
		)
	}
	static async updateTerminalConnectionTimeout(
		request: proto.kerberosec.UpdateTerminalConnectionTimeoutRequest,
	): Promise<proto.kerberosec.UpdateTerminalConnectionTimeoutResponse> {
		return this.makeUnaryRequest(
			"updateTerminalConnectionTimeout",
			request,
			proto.kerberosec.UpdateTerminalConnectionTimeoutRequest.toJSON,
			proto.kerberosec.UpdateTerminalConnectionTimeoutResponse.fromJSON,
		)
	}
	static async updateTerminalReuseEnabled(request: proto.kerberosec.BooleanRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateTerminalReuseEnabled",
			request,
			proto.kerberosec.BooleanRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async getAvailableTerminalProfiles(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.TerminalProfiles> {
		return this.makeUnaryRequest(
			"getAvailableTerminalProfiles",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.TerminalProfiles.fromJSON,
		)
	}
	static subscribeToState(request: proto.kerberosec.EmptyRequest, callbacks: Callbacks<proto.kerberosec.State>): () => void {
		return this.makeStreamingRequest(
			"subscribeToState",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.State.fromJSON,
			callbacks,
		)
	}
	static async toggleFavoriteModel(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"toggleFavoriteModel",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async resetState(request: proto.kerberosec.ResetStateRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"resetState",
			request,
			proto.kerberosec.ResetStateRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async togglePlanActModeProto(request: proto.kerberosec.TogglePlanActModeRequest): Promise<proto.kerberosec.Boolean> {
		return this.makeUnaryRequest(
			"togglePlanActModeProto",
			request,
			proto.kerberosec.TogglePlanActModeRequest.toJSON,
			proto.kerberosec.Boolean.fromJSON,
		)
	}
	static async updateAutoApprovalSettings(
		request: proto.kerberosec.AutoApprovalSettingsRequest,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateAutoApprovalSettings",
			request,
			proto.kerberosec.AutoApprovalSettingsRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateSettings(request: proto.kerberosec.UpdateSettingsRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateSettings",
			request,
			proto.kerberosec.UpdateSettingsRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateSettingsCli(request: proto.kerberosec.UpdateSettingsRequestCli): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateSettingsCli",
			request,
			proto.kerberosec.UpdateSettingsRequestCli.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateTaskSettings(request: proto.kerberosec.UpdateTaskSettingsRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateTaskSettings",
			request,
			proto.kerberosec.UpdateTaskSettingsRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateTelemetrySetting(request: proto.kerberosec.TelemetrySettingRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateTelemetrySetting",
			request,
			proto.kerberosec.TelemetrySettingRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async captureOnboardingProgress(request: proto.kerberosec.OnboardingProgressRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"captureOnboardingProgress",
			request,
			proto.kerberosec.OnboardingProgressRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async setWelcomeViewCompleted(request: proto.kerberosec.BooleanRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"setWelcomeViewCompleted",
			request,
			proto.kerberosec.BooleanRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateInfoBannerVersion(request: proto.kerberosec.Int64Request): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateInfoBannerVersion",
			request,
			proto.kerberosec.Int64Request.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateModelBannerVersion(request: proto.kerberosec.Int64Request): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateModelBannerVersion",
			request,
			proto.kerberosec.Int64Request.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async updateCliBannerVersion(request: proto.kerberosec.Int64Request): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"updateCliBannerVersion",
			request,
			proto.kerberosec.Int64Request.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async dismissBanner(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"dismissBanner",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async trackBannerEvent(request: proto.kerberosec.TrackBannerEventRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"trackBannerEvent",
			request,
			proto.kerberosec.TrackBannerEventRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async installKerberoSecCli(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"installKerberoSecCli",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async checkCliInstallation(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Boolean> {
		return this.makeUnaryRequest(
			"checkCliInstallation",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Boolean.fromJSON,
		)
	}
	static async getProcessInfo(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.ProcessInfo> {
		return this.makeUnaryRequest(
			"getProcessInfo",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.ProcessInfo.fromJSON,
		)
	}
	static async flushPendingState(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"flushPendingState",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async refreshRemoteConfig(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"refreshRemoteConfig",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async testOtelConnection(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.TestConnectionResult> {
		return this.makeUnaryRequest(
			"testOtelConnection",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.TestConnectionResult.fromJSON,
		)
	}
	static async testPromptUploading(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.TestConnectionResult> {
		return this.makeUnaryRequest(
			"testPromptUploading",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.TestConnectionResult.fromJSON,
		)
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.TaskService"
	static async cancelTask(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("cancelTask", request, proto.kerberosec.EmptyRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async cancelQueuedPrompt(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"cancelQueuedPrompt",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async cancelBackgroundCommand(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"cancelBackgroundCommand",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async proceedWhileRunningCommand(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"proceedWhileRunningCommand",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async clearTask(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("clearTask", request, proto.kerberosec.EmptyRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async getTotalTasksSize(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Int64> {
		return this.makeUnaryRequest(
			"getTotalTasksSize",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Int64.fromJSON,
		)
	}
	static async deleteTasksWithIds(request: proto.kerberosec.StringArrayRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"deleteTasksWithIds",
			request,
			proto.kerberosec.StringArrayRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async newTask(request: proto.kerberosec.NewTaskRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest("newTask", request, proto.kerberosec.NewTaskRequest.toJSON, proto.kerberosec.String.fromJSON)
	}
	static async showTaskWithId(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.TaskResponse> {
		return this.makeUnaryRequest(
			"showTaskWithId",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.TaskResponse.fromJSON,
		)
	}
	static async exportTaskWithId(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"exportTaskWithId",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async toggleTaskFavorite(request: proto.kerberosec.TaskFavoriteRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"toggleTaskFavorite",
			request,
			proto.kerberosec.TaskFavoriteRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async getTaskHistory(request: proto.kerberosec.GetTaskHistoryRequest): Promise<proto.kerberosec.TaskHistoryArray> {
		return this.makeUnaryRequest(
			"getTaskHistory",
			request,
			proto.kerberosec.GetTaskHistoryRequest.toJSON,
			proto.kerberosec.TaskHistoryArray.fromJSON,
		)
	}
	static async askResponse(request: proto.kerberosec.AskResponseRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"askResponse",
			request,
			proto.kerberosec.AskResponseRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async editMessageAndRegenerate(
		request: proto.kerberosec.EditMessageAndRegenerateRequest,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"editMessageAndRegenerate",
			request,
			proto.kerberosec.EditMessageAndRegenerateRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async taskFeedback(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"taskFeedback",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async executeQuickWin(request: proto.kerberosec.ExecuteQuickWinRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"executeQuickWin",
			request,
			proto.kerberosec.ExecuteQuickWinRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async deleteAllTaskHistory(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.DeleteAllTaskHistoryCount> {
		return this.makeUnaryRequest(
			"deleteAllTaskHistory",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.DeleteAllTaskHistoryCount.fromJSON,
		)
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.UiService"
	static async scrollToSettings(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.KeyValuePair> {
		return this.makeUnaryRequest(
			"scrollToSettings",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.KeyValuePair.fromJSON,
		)
	}
	static async setTerminalExecutionMode(request: proto.kerberosec.BooleanRequest): Promise<proto.kerberosec.KeyValuePair> {
		return this.makeUnaryRequest(
			"setTerminalExecutionMode",
			request,
			proto.kerberosec.BooleanRequest.toJSON,
			proto.kerberosec.KeyValuePair.fromJSON,
		)
	}
	static async onDidShowAnnouncement(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Boolean> {
		return this.makeUnaryRequest(
			"onDidShowAnnouncement",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Boolean.fromJSON,
		)
	}
	static subscribeToAddToInput(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.String>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAddToInput",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
			callbacks,
		)
	}
	static subscribeToMcpButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMcpButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToMarketplaceButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMarketplaceButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToHistoryButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToHistoryButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToChatButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToChatButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToAccountButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAccountButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToSettingsButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToSettingsButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToWorktreesButtonClicked(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToWorktreesButtonClicked",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToPartialMessage(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.KerberoSecMessage>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToPartialMessage",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.KerberoSecMessage.fromJSON,
			callbacks,
		)
	}
	static async initializeWebview(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"initializeWebview",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static subscribeToRelinquishControl(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToRelinquishControl",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
			callbacks,
		)
	}
	static subscribeToShowWebview(
		request: proto.kerberosec.EmptyRequest,
		callbacks: Callbacks<proto.kerberosec.ShowWebviewEvent>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToShowWebview",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.ShowWebviewEvent.fromJSON,
			callbacks,
		)
	}
	static async getWebviewHtml(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.String> {
		return this.makeUnaryRequest(
			"getWebviewHtml",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.String.fromJSON,
		)
	}
	static async openUrl(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("openUrl", request, proto.kerberosec.StringRequest.toJSON, proto.kerberosec.Empty.fromJSON)
	}
	static async openWalkthrough(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openWalkthrough",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
	static async trackIntent(request: proto.kerberosec.IntentEvent): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest("trackIntent", request, proto.kerberosec.IntentEvent.toJSON, proto.kerberosec.Empty.fromJSON)
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.WebService"
	static async checkIsImageUrl(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.IsImageUrl> {
		return this.makeUnaryRequest(
			"checkIsImageUrl",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.IsImageUrl.fromJSON,
		)
	}
	static async fetchOpenGraphData(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.OpenGraphData> {
		return this.makeUnaryRequest(
			"fetchOpenGraphData",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.OpenGraphData.fromJSON,
		)
	}
	static async openInBrowser(request: proto.kerberosec.StringRequest): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"openInBrowser",
			request,
			proto.kerberosec.StringRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
}
export class WorktreeServiceClient extends ProtoBusClient {
	static override serviceName: string = "kerberosec.WorktreeService"
	static async listWorktrees(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.WorktreeList> {
		return this.makeUnaryRequest(
			"listWorktrees",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.WorktreeList.fromJSON,
		)
	}
	static async createWorktree(request: proto.kerberosec.CreateWorktreeRequest): Promise<proto.kerberosec.WorktreeResult> {
		return this.makeUnaryRequest(
			"createWorktree",
			request,
			proto.kerberosec.CreateWorktreeRequest.toJSON,
			proto.kerberosec.WorktreeResult.fromJSON,
		)
	}
	static async deleteWorktree(request: proto.kerberosec.DeleteWorktreeRequest): Promise<proto.kerberosec.WorktreeResult> {
		return this.makeUnaryRequest(
			"deleteWorktree",
			request,
			proto.kerberosec.DeleteWorktreeRequest.toJSON,
			proto.kerberosec.WorktreeResult.fromJSON,
		)
	}
	static async switchWorktree(request: proto.kerberosec.SwitchWorktreeRequest): Promise<proto.kerberosec.WorktreeResult> {
		return this.makeUnaryRequest(
			"switchWorktree",
			request,
			proto.kerberosec.SwitchWorktreeRequest.toJSON,
			proto.kerberosec.WorktreeResult.fromJSON,
		)
	}
	static async getAvailableBranches(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.BranchList> {
		return this.makeUnaryRequest(
			"getAvailableBranches",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.BranchList.fromJSON,
		)
	}
	static async getWorktreeDefaults(request: proto.kerberosec.EmptyRequest): Promise<proto.kerberosec.WorktreeDefaults> {
		return this.makeUnaryRequest(
			"getWorktreeDefaults",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.WorktreeDefaults.fromJSON,
		)
	}
	static async getWorktreeIncludeStatus(
		request: proto.kerberosec.EmptyRequest,
	): Promise<proto.kerberosec.WorktreeIncludeStatus> {
		return this.makeUnaryRequest(
			"getWorktreeIncludeStatus",
			request,
			proto.kerberosec.EmptyRequest.toJSON,
			proto.kerberosec.WorktreeIncludeStatus.fromJSON,
		)
	}
	static async createWorktreeInclude(
		request: proto.kerberosec.CreateWorktreeIncludeRequest,
	): Promise<proto.kerberosec.WorktreeResult> {
		return this.makeUnaryRequest(
			"createWorktreeInclude",
			request,
			proto.kerberosec.CreateWorktreeIncludeRequest.toJSON,
			proto.kerberosec.WorktreeResult.fromJSON,
		)
	}
	static async checkoutBranch(request: proto.kerberosec.CheckoutBranchRequest): Promise<proto.kerberosec.WorktreeResult> {
		return this.makeUnaryRequest(
			"checkoutBranch",
			request,
			proto.kerberosec.CheckoutBranchRequest.toJSON,
			proto.kerberosec.WorktreeResult.fromJSON,
		)
	}
	static async mergeWorktree(request: proto.kerberosec.MergeWorktreeRequest): Promise<proto.kerberosec.MergeWorktreeResult> {
		return this.makeUnaryRequest(
			"mergeWorktree",
			request,
			proto.kerberosec.MergeWorktreeRequest.toJSON,
			proto.kerberosec.MergeWorktreeResult.fromJSON,
		)
	}
	static async trackWorktreeViewOpened(
		request: proto.kerberosec.TrackWorktreeViewOpenedRequest,
	): Promise<proto.kerberosec.Empty> {
		return this.makeUnaryRequest(
			"trackWorktreeViewOpened",
			request,
			proto.kerberosec.TrackWorktreeViewOpenedRequest.toJSON,
			proto.kerberosec.Empty.fromJSON,
		)
	}
}
