// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.19.1
// source: host/core_connection.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface CoreConnectionMessage {
  hello?: CoreConnectionHello | undefined;
  request?: CoreConnectionRequest | undefined;
  response?: CoreConnectionResponse | undefined;
  cancel?: CoreConnectionCancel | undefined;
  ready?: CoreConnectionReady | undefined;
}

/**
 * The first message from a core. The host accepts it only when token matches
 * the current spawn expectation; instance_id is the core's cross-process lock
 * owner identity and is unique for that spawn.
 */
export interface CoreConnectionHello {
  token: string;
  instanceId: string;
}

export interface CoreConnectionRequest {
  requestId: string;
  service: string;
  method: string;
  messageJson: string;
  isStreaming: boolean;
}

export interface CoreConnectionResponse {
  requestId: string;
  /**
   * Logical response payload. A legal wire encoding for small payloads,
   * though the current core always sends message_json_chunk instead and the
   * host reconstructs this field after all bounded chunks arrive. Receivers
   * must accept both encodings; a response may not mix them.
   */
  messageJson?: string | undefined;
  error?:
    | string
    | undefined;
  /**
   * Ends this request. A streaming response may carry its final payload in one
   * message and then send a payload-free completed response.
   */
  completed: boolean;
  messageJsonChunk?:
    | Uint8Array
    | undefined;
  /** Marks the final chunk of one logical response payload. */
  messageJsonComplete: boolean;
}

export interface CoreConnectionCancel {
  requestId: string;
}

/**
 * Sent by the host only after it authenticates the hello and installs this
 * stream as the current core connection.
 */
export interface CoreConnectionReady {
}

function createBaseCoreConnectionMessage(): CoreConnectionMessage {
  return { hello: undefined, request: undefined, response: undefined, cancel: undefined, ready: undefined };
}

export const CoreConnectionMessage: MessageFns<CoreConnectionMessage> = {
  encode(message: CoreConnectionMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hello !== undefined) {
      CoreConnectionHello.encode(message.hello, writer.uint32(10).fork()).join();
    }
    if (message.request !== undefined) {
      CoreConnectionRequest.encode(message.request, writer.uint32(18).fork()).join();
    }
    if (message.response !== undefined) {
      CoreConnectionResponse.encode(message.response, writer.uint32(26).fork()).join();
    }
    if (message.cancel !== undefined) {
      CoreConnectionCancel.encode(message.cancel, writer.uint32(34).fork()).join();
    }
    if (message.ready !== undefined) {
      CoreConnectionReady.encode(message.ready, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hello = CoreConnectionHello.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = CoreConnectionRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.response = CoreConnectionResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cancel = CoreConnectionCancel.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ready = CoreConnectionReady.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoreConnectionMessage {
    return {
      hello: isSet(object.hello) ? CoreConnectionHello.fromJSON(object.hello) : undefined,
      request: isSet(object.request) ? CoreConnectionRequest.fromJSON(object.request) : undefined,
      response: isSet(object.response) ? CoreConnectionResponse.fromJSON(object.response) : undefined,
      cancel: isSet(object.cancel) ? CoreConnectionCancel.fromJSON(object.cancel) : undefined,
      ready: isSet(object.ready) ? CoreConnectionReady.fromJSON(object.ready) : undefined,
    };
  },

  toJSON(message: CoreConnectionMessage): unknown {
    const obj: any = {};
    if (message.hello !== undefined) {
      obj.hello = CoreConnectionHello.toJSON(message.hello);
    }
    if (message.request !== undefined) {
      obj.request = CoreConnectionRequest.toJSON(message.request);
    }
    if (message.response !== undefined) {
      obj.response = CoreConnectionResponse.toJSON(message.response);
    }
    if (message.cancel !== undefined) {
      obj.cancel = CoreConnectionCancel.toJSON(message.cancel);
    }
    if (message.ready !== undefined) {
      obj.ready = CoreConnectionReady.toJSON(message.ready);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionMessage>, I>>(base?: I): CoreConnectionMessage {
    return CoreConnectionMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionMessage>, I>>(object: I): CoreConnectionMessage {
    const message = createBaseCoreConnectionMessage();
    message.hello = (object.hello !== undefined && object.hello !== null)
      ? CoreConnectionHello.fromPartial(object.hello)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? CoreConnectionRequest.fromPartial(object.request)
      : undefined;
    message.response = (object.response !== undefined && object.response !== null)
      ? CoreConnectionResponse.fromPartial(object.response)
      : undefined;
    message.cancel = (object.cancel !== undefined && object.cancel !== null)
      ? CoreConnectionCancel.fromPartial(object.cancel)
      : undefined;
    message.ready = (object.ready !== undefined && object.ready !== null)
      ? CoreConnectionReady.fromPartial(object.ready)
      : undefined;
    return message;
  },
};

function createBaseCoreConnectionHello(): CoreConnectionHello {
  return { token: "", instanceId: "" };
}

export const CoreConnectionHello: MessageFns<CoreConnectionHello> = {
  encode(message: CoreConnectionHello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionHello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionHello();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoreConnectionHello {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      instanceId: isSet(object.instanceId)
        ? globalThis.String(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.String(object.instance_id)
        : "",
    };
  },

  toJSON(message: CoreConnectionHello): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.instanceId !== "") {
      obj.instanceId = message.instanceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionHello>, I>>(base?: I): CoreConnectionHello {
    return CoreConnectionHello.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionHello>, I>>(object: I): CoreConnectionHello {
    const message = createBaseCoreConnectionHello();
    message.token = object.token ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseCoreConnectionRequest(): CoreConnectionRequest {
  return { requestId: "", service: "", method: "", messageJson: "", isStreaming: false };
}

export const CoreConnectionRequest: MessageFns<CoreConnectionRequest> = {
  encode(message: CoreConnectionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.service !== "") {
      writer.uint32(18).string(message.service);
    }
    if (message.method !== "") {
      writer.uint32(26).string(message.method);
    }
    if (message.messageJson !== "") {
      writer.uint32(34).string(message.messageJson);
    }
    if (message.isStreaming !== false) {
      writer.uint32(40).bool(message.isStreaming);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.service = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.messageJson = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isStreaming = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoreConnectionRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      service: isSet(object.service) ? globalThis.String(object.service) : "",
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      messageJson: isSet(object.messageJson)
        ? globalThis.String(object.messageJson)
        : isSet(object.message_json)
        ? globalThis.String(object.message_json)
        : "",
      isStreaming: isSet(object.isStreaming)
        ? globalThis.Boolean(object.isStreaming)
        : isSet(object.is_streaming)
        ? globalThis.Boolean(object.is_streaming)
        : false,
    };
  },

  toJSON(message: CoreConnectionRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.service !== "") {
      obj.service = message.service;
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.messageJson !== "") {
      obj.messageJson = message.messageJson;
    }
    if (message.isStreaming !== false) {
      obj.isStreaming = message.isStreaming;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionRequest>, I>>(base?: I): CoreConnectionRequest {
    return CoreConnectionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionRequest>, I>>(object: I): CoreConnectionRequest {
    const message = createBaseCoreConnectionRequest();
    message.requestId = object.requestId ?? "";
    message.service = object.service ?? "";
    message.method = object.method ?? "";
    message.messageJson = object.messageJson ?? "";
    message.isStreaming = object.isStreaming ?? false;
    return message;
  },
};

function createBaseCoreConnectionResponse(): CoreConnectionResponse {
  return {
    requestId: "",
    messageJson: undefined,
    error: undefined,
    completed: false,
    messageJsonChunk: undefined,
    messageJsonComplete: false,
  };
}

export const CoreConnectionResponse: MessageFns<CoreConnectionResponse> = {
  encode(message: CoreConnectionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.messageJson !== undefined) {
      writer.uint32(18).string(message.messageJson);
    }
    if (message.error !== undefined) {
      writer.uint32(26).string(message.error);
    }
    if (message.completed !== false) {
      writer.uint32(32).bool(message.completed);
    }
    if (message.messageJsonChunk !== undefined) {
      writer.uint32(42).bytes(message.messageJsonChunk);
    }
    if (message.messageJsonComplete !== false) {
      writer.uint32(48).bool(message.messageJsonComplete);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.completed = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.messageJsonChunk = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.messageJsonComplete = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoreConnectionResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      messageJson: isSet(object.messageJson)
        ? globalThis.String(object.messageJson)
        : isSet(object.message_json)
        ? globalThis.String(object.message_json)
        : undefined,
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
      completed: isSet(object.completed) ? globalThis.Boolean(object.completed) : false,
      messageJsonChunk: isSet(object.messageJsonChunk)
        ? bytesFromBase64(object.messageJsonChunk)
        : isSet(object.message_json_chunk)
        ? bytesFromBase64(object.message_json_chunk)
        : undefined,
      messageJsonComplete: isSet(object.messageJsonComplete)
        ? globalThis.Boolean(object.messageJsonComplete)
        : isSet(object.message_json_complete)
        ? globalThis.Boolean(object.message_json_complete)
        : false,
    };
  },

  toJSON(message: CoreConnectionResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.messageJson !== undefined) {
      obj.messageJson = message.messageJson;
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    if (message.completed !== false) {
      obj.completed = message.completed;
    }
    if (message.messageJsonChunk !== undefined) {
      obj.messageJsonChunk = base64FromBytes(message.messageJsonChunk);
    }
    if (message.messageJsonComplete !== false) {
      obj.messageJsonComplete = message.messageJsonComplete;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionResponse>, I>>(base?: I): CoreConnectionResponse {
    return CoreConnectionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionResponse>, I>>(object: I): CoreConnectionResponse {
    const message = createBaseCoreConnectionResponse();
    message.requestId = object.requestId ?? "";
    message.messageJson = object.messageJson ?? undefined;
    message.error = object.error ?? undefined;
    message.completed = object.completed ?? false;
    message.messageJsonChunk = object.messageJsonChunk ?? undefined;
    message.messageJsonComplete = object.messageJsonComplete ?? false;
    return message;
  },
};

function createBaseCoreConnectionCancel(): CoreConnectionCancel {
  return { requestId: "" };
}

export const CoreConnectionCancel: MessageFns<CoreConnectionCancel> = {
  encode(message: CoreConnectionCancel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionCancel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionCancel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoreConnectionCancel {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
    };
  },

  toJSON(message: CoreConnectionCancel): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionCancel>, I>>(base?: I): CoreConnectionCancel {
    return CoreConnectionCancel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionCancel>, I>>(object: I): CoreConnectionCancel {
    const message = createBaseCoreConnectionCancel();
    message.requestId = object.requestId ?? "";
    return message;
  },
};

function createBaseCoreConnectionReady(): CoreConnectionReady {
  return {};
}

export const CoreConnectionReady: MessageFns<CoreConnectionReady> = {
  encode(_: CoreConnectionReady, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreConnectionReady {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreConnectionReady();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CoreConnectionReady {
    return {};
  },

  toJSON(_: CoreConnectionReady): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CoreConnectionReady>, I>>(base?: I): CoreConnectionReady {
    return CoreConnectionReady.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoreConnectionReady>, I>>(_: I): CoreConnectionReady {
    const message = createBaseCoreConnectionReady();
    return message;
  },
};

/**
 * Carries calls from an external host to the core over the connection that the
 * core opens to the host bridge. This avoids a second listening socket in the
 * core process while preserving unary and response-streaming ProtoBus calls.
 */
export type CoreConnectionServiceDefinition = typeof CoreConnectionServiceDefinition;
export const CoreConnectionServiceDefinition = {
  name: "CoreConnectionService",
  fullName: "host.CoreConnectionService",
  methods: {
    connect: {
      name: "connect",
      requestType: CoreConnectionMessage as typeof CoreConnectionMessage,
      requestStream: true,
      responseType: CoreConnectionMessage as typeof CoreConnectionMessage,
      responseStream: true,
      options: {},
    },
  },
} as const;

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
